[network]

# Local address to listen on
bind = "localhost"

# Local port to listen on
port = 6680

[peer]

# I am the seed
seeds = []

# Maximum number of peers to connect to
max_peer_count = 10

# Number of unhandled messages that are kept waiting in a buffer
max_pending_messages = 32

# Number of messages waiting to be sent to all peers
max_pending_send_to_all = 128

# Period in millis after which heartbeats are sent in case of quiscient period
heartbeat_interval = 1000

[noise]

# TODO: Move this into a separate encrypted keystore.
key = """
-----BEGIN PRIVATE KEY-----
MFECAQEwBQYDK2VwBCIEIJ7pILqR7yBPsVuysfGyofjOEm19skmtqcJYWiVwjKH1
gSEA68zeZuy7PMMQC9ECPmWqDl5AOFj5bi243F823ZVWtXY=
-----END PRIVATE KEY-----
"""
