[network]

# Local address to listen on
bind = "localhost"

# Local port to listen on
port = 6682

[peer]

# Initial peers to connect to
seeds = ["localhost:6680", "localhost:6681"]

# Maximum number of peers to connect to
max_peer_count = 10

# Number of unhandled messages that are kept waiting in a buffer
max_pending_messages = 32

# Number of messages waiting to be sent to all peers
max_pending_send_to_all = 128

# Period in millis after which heartbeats are sent in case of quiscient period
heartbeat_interval = 1000

[noise]

key = """
-----BEGIN PRIVATE KEY-----
MFECAQEwBQYDK2VwBCIEIHpIGDCPu9YvD6IS45GQj2h87Iz50D7oabLrwDC6V9vD
gSEAhpCLOY0BHcCepM6xy2eLYeJLSd7yRQIUuQL4i405qhM=
-----END PRIVATE KEY-----
"""