== FROST Federation

A federation of nodes running FROST to generate threshold signatures
for itself and on the request of clients.

The federation also saves and synchronises data and commands sent by
clients. The federation then runs a priori known validation scheme on
the data before generating a threshold signature.

== System Model

=== Network Connectivity

. A federation of nodes with point to point network connectivity.
. All point to point connections are authenticated and confidential using the Noise framework.
. All point to point connections are reliable with no ordering guarantees.
. Provide an echo-broadcast implementation between all nodes to satisfy the FROST broadcast channel requirements.
. Clocks are synchronised using ntp to satisfy partial synchrony requirements.

=== Round Time

. Round time of 5 seconds [TODO: Determine this if this is enough for
a network of size 100 nodes, and then adjust this as required]


== Federation Clients

. Clients connect to any node in the federation and then send data/commands to that node.
. The federation members synchronise data and commands received from clients.

== Threshold Signatures

. The federation runs preprocessing DKG rounds every fixed interval.
. Threshold signatures are generated Whenever a client requests a one or the federation needs one.

=== Validate Before Signing

. The federation is provided a validation protocol it runs on the synchronised data, before it generates a threshold signature.
. This allows clients to use the federation as a BFT validation and signature generation service.

== Build Status

[link=https://github.com/pool2win/frost-federation/actions/workflows/tests.yml]
image::https://github.com/pool2win/frost-federation/actions/workflows/tests.yml/badge.svg[Rust CI]

== Coverage

Note: Rust code coverage misses a lot of lines. We still share links to the report for transparency

[link=https://codecov.io/gh/pool2win/frost-federation]
image::https://codecov.io/gh/pool2win/frost-federation/graph/badge.svg?token=W3FWIFM232[Codecov]

[link=https://codecov.io/gh/pool2win/frost-federation]
image::https://codecov.io/gh/pool2win/frost-federation/graphs/icicle.svg?token=W3FWIFM232[Codecov]

